<?xml version="1.0"?>
<?xml-model href="http://download.ros.org/schema/package_format3.xsd" schematypens="http://www.w3.org/2001/XMLSchema"?>
<package format="3">
  <name>antobot_devices_camera</name>
  <version>0.0.1</version>
  <description>Camera recorder server and client nodes for Antobot</description>
  <maintainer email="jinhuan.liu@antobot.ai">your_name</maintainer>
  <license>TODO: License declaration</license>

  <buildtool_depend>ament_python</buildtool_depend>

  <depend>rclpy</depend>
  <depend>sensor_msgs</depend>
  <depend>tf2_ros</depend>
  <exec_depend>antobot_camera_msgs</exec_depend>

  <export>
    <build_type>ament_python</build_type>
  </export>
</package>
